# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  setup:
    run: once
    desc: Install dependencies
    dir: "{{.TASKFILE_DIR}}"
    sources:
      - .rtx.toml
      - package.json
      - pnpm-lock.yaml
      - "**/package.json"
    cmds:
      - rtx install 2> /dev/null || true
      - pnpm install

  dev:
    desc: Dev
    deps: [setup]
    cmds:
      - npx astro dev

  build:
    desc: Build the project
    cmds:
      - npx astro build

  fix:
    cmds:
      - npx biome format --write .
      - npx biome lint --skip-errors --apply-unsafe .
