version: "3"

services:
  payload:
    image: node:18-alpine
    ports:
      - "3001:3001"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3001
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING
      STRIPE_SECRET_KEY: sk_test_51HF6DLIEKoo3V8P3HkBmUIDtxZ1THFdXXPYZF9E1S9YEfnUxVz0K4UUPMctmkslZ8SKqaTiK4E4VEepP0iq8qf8j00mhCFSfI6

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
